version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
    - 8080:80

  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase